name: dev
description: A simple command line tool written in dart designed to boost your development experience.
version: 1.0.0

environment:
    sdk: ">=2.15.1 <3.0.0"

dependencies:
    path: ^1.8.1

dev_dependencies:
    lints: ^1.0.0
